# Generated by Django 4.2.7 on 2023-11-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('PG', 'PG'), ('SG', 'SG'), ('SF', 'SF'), ('PF', 'PF'), ('C', 'C')], max_length=2)),
                ('FTM', models.IntegerField()),
                ('FTA', models.IntegerField()),
                ('TWO_PM', models.IntegerField()),
                ('TWO_PA', models.IntegerField()),
                ('THREE_PM', models.IntegerField()),
                ('THREE_PA', models.IntegerField()),
                ('REB', models.IntegerField()),
                ('BLK', models.IntegerField()),
                ('AST', models.IntegerField()),
                ('STL', models.IntegerField()),
                ('TOV', models.IntegerField()),
            ],
        ),
    ]
