# Generated by Django 4.2.7 on 2023-11-14 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorization', models.FloatField()),
                ('effectiveFieldGoalPercentage', models.FloatField()),
                ('trueShootingPercentage', models.FloatField()),
                ('hollingerAssistRatio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ShotStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.FloatField()),
                ('made', models.FloatField()),
                ('shootingPercentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TraditionalStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField()),
                ('rebounds', models.FloatField()),
                ('blocks', models.FloatField()),
                ('assists', models.FloatField()),
                ('steals', models.FloatField()),
                ('turnovers', models.FloatField()),
                ('freeThrows', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='free_throws', to='players.shotstatistics')),
                ('threePoints', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='three_points', to='players.shotstatistics')),
                ('twoPoints', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_points', to='players.shotstatistics')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=50)),
                ('gamesPlayed', models.IntegerField()),
                ('advanced', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.advancedstatistics')),
                ('traditional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.traditionalstatistics')),
            ],
        ),
    ]
